# config/desire_profile.yaml
# Declarative definition of motivation physics

desire_parameters:
  base_desire: 0.5
  decay_rate: 0.03
  reinforcement_gain: 0.15
  frustration_penalty: 0.1

thresholds:
  activation: 0.6
  abandonment: 0.2
  obsession_cap: 1.5
